release: python manage.py collectstatic --noinput || true; python manage.py migrate --noinput
web: python manage.py collectstatic --noinput || true; python manage.py migrate --noinput; gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --access-logfile - --error-logfile -
